{
    "proyectos"[
      {
        proyecto: "50023 ECOPETROL PUERTO GAITÁN 2023",
        idNodoP: 86,
        Codi_parteP: "0",
        idPadreP: 0,
        skuP: "50023",
        nitCliente: "899999068",
        componentes: [
          {
            fecha: "2023-06-20",
            componente:
              " CONSULTORÍA Y ACOMPAÑAMIENTO EMPRESARIAL (Alcances 1, 2 3 y 4)",
            idNodoC: 104,
            Codi_parteC: "17",
            idPadreC: 86,
            skuC: "50023",
            actividades: [
              {
                actividad:
                  "Reunión / logística de bienvenida a los beneficiarios",
                frecuencia: 0,
                entregable: true,
                nombre_entregable: [
                  {
                    id_proceso: 625,
                    Numero: 1,
                    Nom_Entregable: "Listado de asistencia",
                  },
                  {
                    id_proceso: 625,
                    Numero: 2,
                    Nom_Entregable: "Registro fotogratico",
                  },
                  {
                    id_proceso: 625,
                    Numero: 3,
                    Nom_Entregable: "Presentación",
                  },
                ],
                idNodoA: 622,
                Codi_parteA: "625",
                idPadreA: 104,
                skuA: "50023",
                terminada: false,
              },
              {
                actividad: "Actividades de sensibilización de la convocatoria",
                frecuencia: 0,
                entregable: true,
                nombre_entregable: [
                  {
                    id_proceso: 813,
                    Numero: 1,
                    Nom_Entregable: "Soporte de la actividad",
                  },
                ],
                idNodoA: 589,
                Codi_parteA: "813",
                idPadreA: 104,
                skuA: "50023",
                terminada: false,
              },
              {
                actividad: "Gestión de eventos",
                frecuencia: 0,
                entregable: false,
                nombre_entregable: [],
                idNodoA: 617,
                Codi_parteA: "687",
                idPadreA: 104,
                skuA: "50023",
                terminada: false,
              },
              {
                actividad:
                  "Organizar/ Revisión/ gestión documental de las carpetas de los proyectos",
                frecuencia: 2,
                entregable: false,
                nombre_entregable: [],
                idNodoA: 599,
                Codi_parteA: "134",
                idPadreA: 104,
                skuA: "50023",
                terminada: true,
              },
              {
                actividad: "Comité de selección de beneficiarios",
                frecuencia: 0,
                entregable: true,
                nombre_entregable: [
                  {
                    id_proceso: 708,
                    Numero: 1,
                    Nom_Entregable: "Informe de beneficiarios",
                  },
                ],
                idNodoA: 715,
                Codi_parteA: "708",
                idPadreA: 104,
                skuA: "50023",
                terminada: false,
              },
            ],
          },
          {
            fecha: "2023-05-25",
            componente: "ETAPA PRELIMINAR",
            idNodoC: 87,
            Codi_parteC: "14",
            idPadreC: 86,
            skuC: "50023",
            actividades: [
              {
                actividad: "Capacitación al equipo",
                frecuencia: 0,
                entregable: false,
                nombre_entregable: [],
                idNodoA: 91,
                Codi_parteA: "107",
                idPadreA: 87,
                skuA: "50023",
                terminada: true,
              },
              {
                actividad: "Participar Foro de proyectos",
                frecuencia: 0,
                entregable: false,
                nombre_entregable: [],
                idNodoA: 197,
                Codi_parteA: "128",
                idPadreA: 87,
                skuA: "50023",
                terminada: false,
              },
              {
                actividad: "Participación en reuniones administrativas ",
                frecuencia: 1,
                entregable: false,
                nombre_entregable: [],
                idNodoA: 309,
                Codi_parteA: "124",
                idPadreA: 87,
                skuA: "50023",
                terminada: false,
              },
              {
                actividad:
                  "Organizar/ Revisión/ gestión documental de las carpetas de los proyectos",
                frecuencia: 2,
                entregable: false,
                nombre_entregable: [],
                idNodoA: 307,
                Codi_parteA: "134",
                idPadreA: 87,
                skuA: "50023",
                terminada: false,
              },
              {
                actividad:
                  "Gestión legal, contable, financiera y administrativa de los proyectos / Requerimiento",
                frecuencia: 0,
                entregable: true,
                nombre_entregable: [
                  {
                    id_proceso: 700,
                    Numero: 1,
                    Nom_Entregable: "Soporte de la actividad",
                  },
                ],
                idNodoA: 302,
                Codi_parteA: "700",
                idPadreA: 87,
                skuA: "50023",
                terminada: false,
              },
              {
                actividad: "Gestión/Legalización de gastos /de los Proyectos",
                frecuencia: 1,
                entregable: false,
                nombre_entregable: [],
                idNodoA: 303,
                Codi_parteA: "112",
                idPadreA: 87,
                skuA: "50023",
                terminada: false,
              },
            ],
          },
        ],
      }
    ];
  }
  